# build:
#   version: "2.0"

# account:
#   message: "Welcome to EazyBank accounts related QA APIs "
#   contactDetails:
#     name: "Smitha Ray - QA Lead"
#     email: "smitha@eazybank.com"
#   onCallSupport:
#     - (666) 265-3765
#     - (666) 734-8371

eureka:
  client:
    serviceUrl:
      # defaultZone: http://192.168.100.221:30743/eureka/
      defaultZone: http://localhost:9201/eureka/
