# springboot-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team7-config-kkh
  namespace: group1-team7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team7-config-kkh
  template:
    metadata:
      labels:
        app: team7-config-kkh
    spec:
      containers:
      - name: team7-config-kkh
        image: k8s-vga-worker1:5000/team7-config-kkh:latest
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: team7-config-kkh
  namespace: group1-team7
spec:
  selector:
    app: team7-config-kkh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9200
      nodePort: 30742
  type: NodePort

---
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://team7-zipkin-kkh:80/api/v2/spans

---
metrics:
  export:
    prometheus:
      enable: true
