# springboot-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-kkh
  namespace: group1-team7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-kkh
  template:
    metadata:
      labels:
        app: config-kkh
    spec:
      containers:
      - name: config-kkh
        image: k8s-vga-worker1:5000/team7-config-kkh:latest
        imagePullPolicy: Always #IfNotPresent
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: config-kkh
  namespace: group1-team7
spec:
  selector:
    app: config-kkh
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 30742
  type: NodePort